import './css/reset.css';
import './css/style.css';
import './css/editarea.css';
import './css/switch-btn.css';
import './css/login.css';
// import 'vue';
// import '../vendors/js/av-min';
import '../vendors/laydate/laydate';
import './js/init-av';
import './js/editarea';
import './js/switch-btn';
import './js/header';
import './js/preview-header';
import './js/resume';
import './js/aside';
import './js/login';
import './js/signup';
import './js/signup-success';
import './js/app';
import './js/init-laydata';